server:
  port: 7777
spring:
  application:
    name: getway-server
  cloud:
    nacos:
      discovery:    #nacos注册中心相关配置
        server-addr: localhost:8848
        username: nacos
        password: nacos
