server:
  port: 9095
spring:
  application:
    name: consumer-server
  cloud:
    nacos:
      discovery:    #nacos注册中心相关配置
        server-addr: localhost:8848
        username: nacos
        password: nacos
  mvc:
    format:
      date-time: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource: #数据库连接池的配置
    url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: 127.0.0.1:9200
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.nchu.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
